import { Layout } from "@/src/entities/Client";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import '@styles'

const roboto = Roboto({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.className}>
      <body>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
